using System.Collections;
using System.Collections.Generic;
using System.IO;
using UnityEngine;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.LowLevel;

namespace HappyToy.V2
{
    // Test-only component added explicitly in Play mode. Each stair starts at a known approach;
    // movement up and down is generated by W input through PlayerMotor/CharacterController.
    public sealed class MultiFloorWalkProbe : MonoBehaviour
    {
        public bool Done {get;private set;}
        public string Failure {get;private set;}="";
        Keyboard keyboard; PlayerMotor player;
        InputSettings.BackgroundBehavior oldBehavior;
        readonly List<string> legs=new List<string>();
        IEnumerator Start()
        {
            Application.runInBackground=true;
            oldBehavior=InputSystem.settings.backgroundBehavior;
            InputSystem.settings.backgroundBehavior=InputSettings.BackgroundBehavior.IgnoreFocus;
            keyboard=InputSystem.AddDevice<Keyboard>();player=GameSession.Current.player;GameSession.Current.Shell.Begin();
            yield return null;
            Place(new Vector3(29.8f,.05f,10));
            yield return Walk(new Vector3(29.8f,5,22),"upper ascent");
            if(Failure=="")yield return Walk(new Vector3(29.8f,0,10),"upper descent");
            if(Failure=="")
            {
                Place(new Vector3(13.8f,.05f,-10));
                yield return Walk(new Vector3(13.8f,-5,-22),"basement descent");
                if(Failure=="")yield return Walk(new Vector3(13.8f,0,-10),"basement ascent");
            }
            InputSystem.QueueStateEvent(keyboard,new KeyboardState());
            var json=Newtonsoft.Json.JsonConvert.SerializeObject(new{passed=Failure==""&&legs.Count==4,failure=Failure,legs,position=player.transform.position.ToString(),player.MovementUpdates},Newtonsoft.Json.Formatting.Indented);
            File.WriteAllText("Verification/annex/stair-input.json",json);Done=true;GameSession.Current.Shell.Pause();
            InputSystem.RemoveDevice(keyboard);keyboard=null;InputSystem.settings.backgroundBehavior=oldBehavior;
        }
        void Place(Vector3 p){var cc=player.GetComponent<CharacterController>();cc.enabled=false;player.transform.position=p;cc.enabled=true;}
        IEnumerator Walk(Vector3 target,string label)
        {
            float deadline=Time.realtimeSinceStartup+20;
            while(Time.realtimeSinceStartup<deadline)
            {
                var delta=target-player.transform.position;float height=Mathf.Abs(delta.y);delta.y=0;
                if(delta.magnitude<.3f&&height<.4f){legs.Add(label);yield break;}
                player.transform.rotation=Quaternion.LookRotation(delta.normalized);
                InputSystem.QueueStateEvent(keyboard,new KeyboardState(Key.W));
                yield return null;
            }
            Failure=label+" stalled at "+player.transform.position;
        }
        void OnDestroy(){if(keyboard!=null){InputSystem.RemoveDevice(keyboard);InputSystem.settings.backgroundBehavior=oldBehavior;}}
    }
}
